test:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
  solr:
    url: http://127.0.0.1:8983/solr/test
development:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@fake/fedora
  solr:
    url: http://fake/solr/development
production:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@prodfake/fedora
  solr:
    url: http://prodfake/solr
